w:
	g++ *.cpp -m32 -static -I D:\\MSvscodeprojects\\MyLibsAndSdk\\npcap_sdk_1_13\\Include -I . -L D:\\MSvscodeprojects\\MyLibsAndSdk\\npcap_sdk_1_13\\Lib -l wpcap -l ws2_32 -l Packet -o MyRouter.exe
test:
	g++ *.cpp -m32 -I D:\\MSvscodeprojects\\MyLibsAndSdk\\npcap_sdk_1_13\\Include -I . -L D:\\MSvscodeprojects\\MyLibsAndSdk\\npcap_sdk_1_13\\Lib -l wpcap -l ws2_32 -l Packet -o MyRouter.exe